### ISSUE TITLE
Parsing cookies with incorrect format

### ISSUE THREAD

**Issue by aquiladev** [aspnet/HttpAbstractions#580]
Hi everyone,

I try to implement custom authentication provider and the server which I use as OAuth server calls my endpoint with bunch of cookies. There is one cookie looks like: 
`DevServer{fb55f50d-593f-4db8-bc9f-e0ec7e9ea7ee}=Division=1;`
As a result `Request.Cookies[cookieName]` can find anything, because cookies parser have not recognized anything and `Request.Cookies` is empty.
How can I solve the problem?
PS Would be better for me to skip incorrect cookies...

**Comment by Tratcher** [comment]
Already addressed in RC2 https://github.com/aspnet/HttpAbstractions/issues/515

**Comment by aquiladev** [comment]
Hi Tratcher,
We updated to RC2 but still have the problem. Here is our HeaderCookie: `.AspNet.Cookies=CfDJ8NqOhcidLVVNiN0GJxBiQJ2IGOUFyq2C6v9xKAo6-OXhOgvyc_iBg2Wc45N7QXvxgh2XPFCKLjRkSs786D4RcFtFKPbxiNiZdxjYFXB7PSxwWcUTQsEddybqfEaHlxXiwGqgnIJD7dLpVwB8Og5CpklyosUpJo4CKD2F9SuruGHkUsfkQlNeit70mmDDpLG_ifDA1-EvJwSfdZpaWBbjY8eaRKdJcf9jPmuF7LOWap0b8ILZ3aU4MVywCEKkfcl9aEdv5WjAgsMGNSM2ETYvofnnxlR2I8Z4McgD6VlPecuJd0Es6tJClhaq0WOKxmFJwWghzh1Em1daPyENPbGWyF9eiyubjJOr0fgJmCFWVgS7FbWgD430ploEuxEAq3Wj9CodcQ48hSq_s51nqJL5j1m-dnHmkhX7DMVyg3cWUtE_-AcJ0WbjofG4FrMfCi6mPWWL3tPy6Za2EBmrhECN9mZ-x10_exBKJQGSQ-MPR7vPy-LEUgTryV_0H-6b2avJKM7bB6cB5v5x6OSDmlAes0qQrCz9YYeK5xOHljsxL3aR_-_yon12dz_mz2a8fTgkzNwVfKk8-orUf2OAPKS4bXn41D5YFmlvdmlJvH3XEA78sW8Br2zGIMO9eYNfdb1A5XWbFzOmj2E-qOl86vGr5P04y0MWIiVYlciDVj0RDgHKa_IS2GCqpXQXzWl5mzHShlgJ3nld_S6Pgpg0PQXsqvCt10jXoY5boGucacabx3fdPBveI5X4TYBcQcKMzZSI-WSIgwnAsbxHvXjUbetvj4XYiAbKJ-PtVQubhwd6hVDD3QGMB8uf1uTFx0O6NftwEKsyVYi3JYtQW3ZAwgJG5_u2_VUxFtTFwNxgM3exeeTlurMdW7ryXsg6AKtf-v5dt2cte0_XUu70LZVbM6zfT5sLfgwkpgKEWMGbxoYz7cF9ue43q4wbZPiB9rKvV109DEbd51RggZHXgnukTjtAlY8SVx08pG3Dl3Or4_A8JqEtyo8Vbw5fIVLas23v_x6j3lj615YNJe3mdODVY3dqQ4ZZPBLiD-iCodZTK4GghQls0ae-QJMPI3AldEgMH_eZSzjer59gbQMmcJqUHqc68qSmpEh2ou1yPgjcgrE8egnp52dbJoWOLniVdKqmCgBA64jz0YliBDTPAzZin4So_ELpn9SyWuSFhLPNbnXrFsKVwDA9ALTgwftXbj8dWnhsPfctxzjpk1FfXLD17HOKi-UYGueo6m4_K-vOjZcozs9yNvTK9ghcCgCzdUaUtPRfjYSLOeNtYV_jnEcR0aZC8IF6wHNcGCMfPlkTtBCi_TOpugrhdkYvXknB784zY9X1zarPP_x9NtcvAP9Tl20IuQcNN6tJ_0dxD6A5dogvq2uD6ppIxhUxCPEN6Sxbu9ODHrxR99iiK3i_odPVQMZKwwRca2uWN06CQZt7o1SqZjpXkyaxLMHiJXyIt2Jn7yJWWYFwc_4N0zFt4JDkG9jqKHbG0X1UVnL97Yn7M1_V1rz09wfi-4Hi-AWaTEVARHUAvAaNXltZFpMR007W6olUt1aB5qtzJ0zX_VSSmh7MyR6Y71Y2AeRcWCiAZm_LyyHZDXloRbrsz3efUaO1js3avv6aiA9H9aL8mutImTLGwQz38fYAjO-QbM2OKcnRyv4A56rjf6GnrqbDTzJckrr9x1cqhpVToOBr4qf5np8XdNuyhu58c4kE-834bBTbBhc2GOxVbsfSqrgghK5gSKM5ZOAs9q15KqxlByWX3ph6-cPUc5Mdr_ZXTL01p5-FPB-PHSyuRRf9Yd9PMgQs6SH-n9Et_gFeOZ3kNVuE78ObIAKxJqSCN28ZyMA1_SlKc0FgIpmXbpNCKfzmTIvB-L6eXxWi3in1JudFcftBjnTknbcZ8FyMCsqYT0_uxxLCqGnufF1lM7CE736w69eUFBk9_xwBZmTFva1FJq1f3owr0xnq0Si3RSnmE41wJNrq2Y8SsS-oSJ8G3g4HVvV9nPL9tBEDDM6Xl76SBE-pnPJUczAI; ASP.NET_SessionId=e42v5zwqwcgf3ma1v4tshyyg; DevServer{3b8e85ff-b3ce-4e56-913d-74c2b218b8c3}=Division=1; DevOnlineLogin=D6ADC7D9C716DC5C07559BC0950EE0273472C6D7E0A3DC5EA6FB19E036A25A523139F938E8C5DAA3B339E3849CF113BFEE1A4A371C290C742317B8E4E8EE80E50D153FB3920DD5CE716EDE40D98ECA9FEB2061489874B31B5CD798A94B7E2A22B3844394795B4CE4B79325E053952DD83D5A453317BA1F66913614D397685A4414A6220D4634EB9220A039F6FC5A1A616C2E4F42CDFCC3909688D8C594791CF0; DevServer{7f72cb74-bd99-41c9-856a-e7c0bae3495c}=Division=21; .AspNet.Correlation.DevOnline=b__rIQkD-ajmlkArEZJ6hyvhyepB_XdIPdZkDNlyq04`

`Request.Cookies` still empty
